name: Blacksmith CI

on:
    push

jobs:
  build_image:
    
    runs-on: "internal-4vcpu-ubuntu-2404"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: test
        run: echo hello
