name: Blacksmith CI

on:
    workflow_dispatch:
      inputs:
        heavy_build:
          description: "Run heavy build tasks"
          type: boolean
          required: false
          default: false

jobs:
  build_image:
    strategy:
      matrix:
        runner: ["development", "blacksmith-4vcpu-ubuntu-2404"]
    
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
        env:
          HEAVY_BUILD: ${{ inputs.heavy_build }}
